var nav_170tree = WpNavBar.readTree({
"childArray" : [
{   'sDescription':'Strona główna',
'sTitle':'Strona główna',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'index.html',
'sTarget':'_self'
},
{   'sDescription':'Wstęp',
'sTitle':'Wstęp',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'wstep.html',
'sTarget':'_self'
},
{   'sDescription':'Ludność żydowska na Podlasiu',
'sTitle':'Ludność żydowska',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'ludnosc-zydowska-na-podlasiu.html',
'sTarget':'_self',"childArray" : [
{   'sDescription':'Osadnictwo i organizacja życia',
'sTitle':'Osadnictwo i organizacja życia',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Osadnictwo-i-organizacja-zycia.html',
'sTarget':'_self'
},
{   'sDescription':'Aktywność gospodarcza',
'sTitle':'Aktywność gospodarcza',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Aktywnosc-gospodarcza.html',
'sTarget':'_self'
},
{   'sDescription':'Życie społeczno – polityczne',
'sTitle':'Życie społeczno – polityczne',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Zycie-spoleczno-polityczne.html',
'sTarget':'_self'
}]
},
{   'sDescription':'Hitlerowski system okupacyjny',
'sTitle':'System okupacyjny',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Hitlerowski-system-okupacyjny.html',
'sTarget':'_self',"childArray" : [
{   'sDescription':'Działania wojenne',
'sTitle':'Działania wojenne',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Dzialania-wojenne.html',
'sTarget':'_self'
},
{   'sDescription':'Administracja cywilna',
'sTitle':'Administracja-cywilna',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Administracja-cywilna.html',
'sTarget':'_self'
},
{   'sDescription':'Policja',
'sTitle':'Policja',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Policja.html',
'sTarget':'_self'
},
{   'sDescription':'Wehrmacht',
'sTitle':'Wehrmacht',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Wehrmacht.html',
'sTarget':'_self'
}]
},
{   'sDescription':'Zagłada Żydów na Podlasiu, Holocaust',
'sTitle':'Zagłada Żydów',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Zaglada-Zydow-na-Podlasiu.html',
'sTarget':'_self',"childArray" : [
{   'sDescription':'Getta',
'sTitle':'Getta',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Getta.html',
'sTarget':'_self'
},
{   'sDescription':'Działania eksterminacyjne batalionu policyjnego 101',
'sTitle':'Działania eksterminacyjne batalionu policyjnego 101',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Batalion-101.html',
'sTarget':'_self'
},
{   'sDescription':'Obozy pracy',
'sTitle':'Obozy pracy',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Obozy-pracy.html',
'sTarget':'_self'
},
{   'sDescription':'Egzekucje',
'sTitle':'Egzekucje',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Egzekucje.html',
'sTarget':'_self'
}]
},
{   'sDescription':'Zakończenie',
'sTitle':'Zakończenie',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Zakonczenie.html',
'sTarget':'_self'
},
{   'sDescription':'Bibliografia',
'sTitle':'Bibliografia',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Bibliografia.html',
'sTarget':'_self'
},
{   'sDescription':'Spis zdjęć i map',
'sTitle':'Spis zdjęć i map',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Spis-zdjec-i-map.html',
'sTarget':'_self'
},
{   'sDescription':'Stare zdjęcia',
'sTitle':'Stare zdjęcia',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'Stare-Zdjecia.html',
'sTarget':'_self'
},
{   'sTitle':'Napisz do nas',
'bIsExternal':true,
'bIsWebPath':true,
'sUrl':'feedback.html',
'sTarget':'_self'
}]
});
